local M = {}

function M.build_main_bootstrap()
	return table.concat({
		'local app = require("app")',
		'local view = require("view")',
		'local web = require("runtime.stdlib.web")',
		"",
		"local function render_response(resp, depth)",
		"  depth = depth or 0",
		"  if depth > 8 then",
		"    return web.dev_error_html({",
		'      _type = "crash",',
		'      err = "redirect_loop",',
		'      trace = "Redirect depth exceeded",',
		"    })",
		"  end",
		"",
		"  if resp == nil then",
		"    return web.dev_error_html({",
		'      _type = "crash",',
		'      err = "nil_response",',
		'      trace = "Application returned nil",',
		"    })",
		"  end",
		"",
		'  if resp._type == "render" then',
		"    return view.render(resp.view, resp.data or {}, {})",
		"  end",
		"",
		'  if resp._type == "redirect" then',
		'    return render_response(app.dispatch("GET", resp.path, ""), depth + 1)',
		"  end",
		"",
		'  if resp._type == "error" or resp._type == "crash" then',
		"    return web.dev_error_html(resp)",
		"  end",
		"",
		'  if resp._type == "not_found" then',
		'    return [[<main class="phone-screen phone-screen-scroll" data-phone-title="Fuwa Gomen"><section class="phone-section phone-safe-all"><div class="phone-stack"><h1>Not found</h1><p>The requested route was not found.</p></div></section></main>]]',
		"  end",
		"",
		'  if type(resp) == "string" then',
		"    return resp",
		"  end",
		"",
		"  return tostring(resp)",
		"end",
		"",
		"function handle_request(method, path, body)",
		"  return render_response(app.dispatch(method, path, body))",
		"end",
		"",
		"if not __fuwa_is_request then",
		'  set_html(render_response(app.dispatch("GET", "/", "")))',
		"end",
		""
	}, "\n")
end

return M
