// @ts-nocheck
// fuwa-gomen / browser.js
// Generated from hooks/*.js. Do not edit this file by hand.

// --- hooks/style.js ---
(function () {
	'use strict';
})();

// --- hooks/bootstrap.js ---
(function () {
	'use strict';

	const G = window.FuwaGomen || (window.FuwaGomen = {});

	const loadOnce = (id, createNode) => {
		if (document.getElementById(id)) return;
		const node = createNode();
		node.id = id;
		document.head.appendChild(node);
	};

	const ensureExternalDependencies = () => {
		loadOnce('fuwa-gomen-fonts', () => {
			const link = document.createElement('link');
			link.rel = 'stylesheet';
			link.href =
				'https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c:wght@500;700;800;900&family=Nunito:wght@600;700;800;900&display=swap';
			return link;
		});
		loadOnce('fuwa-gomen-gsap', () => {
			const script = document.createElement('script');
			script.src = '/vendor/gsap/gsap-3.15.0.min.js';
			return script;
		});
	};

	if (typeof window.__fuwaGomenCleanup === 'function') {
		try {
			window.__fuwaGomenCleanup();
		} catch (error) {
		}
		window.__fuwaGomenCleanup = null;
	}

	ensureExternalDependencies();

	const root = document.getElementById('gomen');

	G.bootstrap = {
		root,
		queryRef: (name) => (root ? root.querySelector(`[data-ref="${name}"]`) : null),
		queryRefs: (name) => (root ? Array.from(root.querySelectorAll(`[data-ref="${name}"]`)) : [])
	};
})();

// --- hooks/content.js ---
(function () {
	'use strict';

	const G = window.FuwaGomen || (window.FuwaGomen = {});

	const blush = (s) => `˶${s}˶`;

	G.content = {
		FACES: {
			neutral: `( ${blush('• ᵕ •')} )`,
			stern: '( ¬_¬ )',
			annoyed: '（ꐦ ¬_¬ ）',
			tantrum: '(ᗒ ᗣ ᗕ)՞',
			worried: `( ${blush('˃ ⤙ ˂')} )`,
			happy: `( ${blush('≧ ᗜ ≦')} )`,
			crying: '( ╥﹏╥ )',
			open: `( ${blush('• 〇 •')} )`,
			chew: `( ${blush('> ﹏ <')} )`,
			angry: '( ಠ ∧ ಠ )'
		},
		COPY: {
			neutral: { jp: 'ふむ…', en: 'Mama is watching.' },
			stern: { jp: 'こら。', en: 'Behave yourself.' },
			annoyed: { jp: 'やめてって。', en: 'Quit poking me!' },
			tantrum: { jp: 'もう！知らない！', en: "That's IT!" },
			worried: { jp: 'あぶないよ…', en: 'Money is low...' },
			happy: { jp: 'えらいね！', en: 'Good job saving!' },
			crying: { jp: 'ぜんぶ使ったの…', en: 'Papa is crying...' },
			refuse: { jp: 'おかね、ない！', en: 'No money left!' }
		},
		ITEMS: [
			{ id: 'onigiri', icon: '🍙', name: 'Onigiri', price: 50 },
			{ id: 'ramen', icon: '🍜', name: 'Ramen', price: 120 },
			{ id: 'takoyaki', icon: '🐙', name: 'Takoyaki', price: 200 },
			{ id: 'sushi', icon: '🍣', name: 'Sushi', price: 300 }
		],
		CONFIG: {
			allowance: 1000,
			decayMs: 4000,
			flyMs: 520,
			chewMs: 420
		}
	};
})();

// --- hooks/mood.js ---
(function () {
	'use strict';

	const G = window.FuwaGomen || (window.FuwaGomen = {});

	G.mood = {
		derive(balance, pokes) {
			const F = G.content.FACES;
			const C = G.content.COPY;
			let key;

			if (balance <= 0) key = 'crying';
			else if (pokes >= 5) key = 'tantrum';
			else if (balance < 300) key = 'worried';
			else if (pokes >= 3) key = 'annoyed';
			else if (pokes >= 1) key = 'stern';
			else if (balance >= 800) key = 'happy';
			else key = 'neutral';

			return {
				moodKey: key,
				face: F[key],
				jp: C[key].jp,
				en: C[key].en,
				papa: balance <= 0
			};
		}
	};
})();

// --- hooks/fx.js ---
(function () {
	'use strict';

	const G = window.FuwaGomen || (window.FuwaGomen = {});

	G.fx = {
		createFx(root, queryRef) {
			const cfg = G.content.CONFIG;

			const flyFoodToMouth = (foodEl, onArrive, onDone) => {
				const gsap = window.gsap;
				const mouth = queryRef('mouth');
				if (!gsap || !foodEl || !mouth) {
					if (onArrive) onArrive();
					if (onDone) onDone();
					return;
				}

				const icon = foodEl.querySelector('.fg-food-icon') || foodEl;
				const fr = icon.getBoundingClientRect();
				const mr = mouth.getBoundingClientRect();
				const clone = icon.cloneNode(true);

				clone.style.position = 'fixed';
				clone.style.left = `${fr.left}px`;
				clone.style.top = `${fr.top}px`;
				clone.style.margin = '0';
				clone.style.zIndex = '9999';
				clone.style.pointerEvents = 'none';
				document.body.appendChild(clone);

				const dx = mr.left + mr.width / 2 - (fr.left + fr.width / 2);
				const dy = mr.top + mr.height / 2 - (fr.top + fr.height / 2);
				const total = cfg.flyMs / 1000;

				let arrived = false;
				const arrive = () => {
					if (arrived) return;
					arrived = true;
					if (onArrive) onArrive();
				};

				gsap
					.timeline({
						onComplete: () => {
							clone.remove();
							if (onDone) onDone();
						}
					})
					.to(clone, {
						x: dx * 0.6,
						y: dy * 0.6 - 28,
						scale: 1.4,
						duration: total * 0.6,
						ease: 'power1.out'
					})
					.add(arrive)
					.to(clone, {
						x: dx,
						y: dy,
						scale: 0.2,
						opacity: 0,
						duration: total * 0.4,
						ease: 'power1.in'
					});
			};

			const chew = () => {
				const gsap = window.gsap;
				const mouth = queryRef('mouth');
				if (!gsap || !mouth) return;
				gsap.fromTo(
					mouth,
					{ scale: 1 },
					{ scale: 1.12, duration: cfg.chewMs / 1000 / 2, yoyo: true, repeat: 1, ease: 'power1.inOut' }
				);
			};

			const pokeReact = () => {
				const gsap = window.gsap;
				if (!gsap || !root) return;
				gsap.fromTo(root, { x: 0 }, { x: -6, duration: 0.05, yoyo: true, repeat: 5, ease: 'power1.inOut' });
			};

			const spit = (foodEl) => {
				const gsap = window.gsap;
				if (!gsap || !foodEl) return;
				gsap.fromTo(foodEl, { y: 0 }, { y: -8, duration: 0.08, yoyo: true, repeat: 3, ease: 'power1.out' });
			};

			return { flyFoodToMouth, chew, pokeReact, spit };
		}
	};
})();

// --- hooks/game.js ---
(function () {
	'use strict';

	const G = window.FuwaGomen || (window.FuwaGomen = {});

	G.createScope = function createScope(serverData) {
		const boot = G.bootstrap;
		const C = G.content;
		const cfg = C.CONFIG;
		const fx = G.fx.createFx(boot.root, boot.queryRef);

		const byId = {};
		C.ITEMS.forEach((item) => {
			byId[item.id] = item;
		});

		const persist = (url) => {
			try {
				const xhr = new XMLHttpRequest();
				xhr.open('GET', url);
				xhr.send();
			} catch (error) {
			}
		};

		const scope = {
			balance: Number.isFinite(serverData.balance) ? serverData.balance : cfg.allowance,
			spent: Number.isFinite(serverData.spent) ? serverData.spent : 0,
			pokes: Number.isFinite(serverData.pokes) ? serverData.pokes : 0,
			counts: {},
			animating: false,
			animatedTotal: 0,
			refusing: false,
			eatingPhase: null,

			get moodKey() {
				return G.mood.derive(this.balance, this.pokes).moodKey;
			},
			get face() {
				if (this.refusing) return C.FACES.angry;
				if (this.eatingPhase) return C.FACES[this.eatingPhase];
				return G.mood.derive(this.balance, this.pokes).face;
			},
			get currentMood() {
				if (this.refusing) return C.COPY.refuse;
				const derived = G.mood.derive(this.balance, this.pokes);
				return { jp: derived.jp, en: derived.en };
			},
			get papaVisible() {
				return this.balance <= 0;
			},
			get barPercent() {
				return Math.max(0, Math.min(100, this.balance / (cfg.allowance / 100)));
			},
			get barText() {
				return `¥${this.balance} · spent ¥${this.spent}`;
			},
			get receiptRows() {
				return C.ITEMS.filter((item) => this.counts[item.id]).map((item) => ({
					id: item.id,
					icon: item.icon,
					name: item.name,
					qty: this.counts[item.id],
					lineTotal: this.counts[item.id] * item.price
				}));
			},
			get total() {
				return this.receiptRows.reduce((sum, row) => sum + row.lineTotal, 0);
			},
			get totalText() {
				return `-¥${Math.round(this.animatedTotal)}`;
			},

			animateTotal(target) {
				const gsap = window.gsap;
				if (!gsap) {
					this.animatedTotal = target;
					return;
				}
				gsap.to(this, { animatedTotal: target, duration: 0.45, ease: 'power1.out' });
			},

			feed(id, event) {
				if (this.animating) return;
				const item = byId[id];
				if (!item) return;
				const foodEl = event && event.currentTarget;

				if (this.balance < item.price) {
					this.refusing = true;
					fx.spit(foodEl);
					window.setTimeout(() => {
						this.refusing = false;
					}, 900);
					return;
				}

				this.animating = true;
				this.eatingPhase = 'open';

				fx.flyFoodToMouth(
					foodEl,
					() => {
						this.balance -= item.price;
						this.spent += item.price;
						this.counts[id] = (this.counts[id] || 0) + 1;
						this.animateTotal(this.total);
						this.eatingPhase = 'chew';
						fx.chew();
					},
					() => {
						this.animating = false;
						this.eatingPhase = null;
						persist(`/buy/${id}`);
					}
				);
			},

			poke() {
				this.pokes += 1;
				fx.pokeReact();
				persist('/poke');
			},

			pet() {
				this.pokes = 0;
				persist('/calm');
			},

			askPapa() {
				this.balance = cfg.allowance;
				this.spent = 0;
				this.pokes = 0;
				this.counts = {};
				this.animateTotal(0);
				persist('/reset');
			}
		};

		const seed = boot.queryRef('seed');
		if (seed) {
			seed.querySelectorAll('[data-id]').forEach((el) => {
				const id = el.getAttribute('data-id');
				if (id && byId[id]) scope.counts[id] = (scope.counts[id] || 0) + 1;
			});
			seed.remove();
		}
		scope.animatedTotal = scope.total;

		const decayTimer = window.setInterval(() => {
			if (scope.pokes > 0) {
				scope.pokes -= 1;
				persist('/cooldown');
			}
		}, cfg.decayMs);

		window.__fuwaGomenCleanup = () => {
			window.clearInterval(decayTimer);
			window.__fuwaGomenCleanup = null;
		};

		return scope;
	};

	let booted = false;
	let retry_timer = null;

	function dependenciesReady() {
		return (
			window.PetiteVue &&
			typeof window.PetiteVue.createApp === 'function' &&
			window.htmx &&
			typeof window.htmx.process === 'function'
		);
	}

	function mount(scope) {
		const isTenantRuntime = document.body && document.body.dataset && document.body.dataset.browserRuntime === 'tenant';
		if (!(scope instanceof Element) || isTenantRuntime) {
			return;
		}

		try {
			window.PetiteVue.createApp().mount(scope);
		} catch (error) {
			console.error('[fuwa-gomen] petite-vue mount failed', error);
		}

		if (window.htmx && window.htmx.config) {
			window.htmx.config.allowScriptTags = false;
		}

		if (window.htmx && typeof window.htmx.process === 'function') {
			window.htmx.process(scope);
		}
	}

	function handleSwap(event) {
		mount(event.detail?.target || event.target || document.body);
	}

	document.addEventListener('htmx:afterSwap', handleSwap);

	function boot() {
		document.documentElement.dataset.fuwaBrowser = 'fuwa-gomen';

		if (!dependenciesReady()) {
			if (!retry_timer) {
				retry_timer = setTimeout(function () {
					retry_timer = null;
					boot();
				}, 16);
			}
			return;
		}

		if (booted) {
			return;
		}

		booted = true;
		mount(document.body);
	}

	if (document.readyState === 'loading') {
		document.addEventListener('DOMContentLoaded', boot, { once: true });
	} else {
		boot();
	}
})();
