// @ts-nocheck
// fuwa-gomen / browser.js
// Generated from hooks/*.js. Do not edit this file by hand.

// --- hooks/style.js ---
(function () {
	'use strict';
	// Styling lives in UnoCSS utility classes (scanned live from views/*.fuwa
	// markup by the runtime loaded in views/layout.fuwa) plus a small static
	// <style> block in views/layout.fuwa for the handful of rules that aren't
	// expressible as utilities: pseudo-elements, CSS custom properties, the
	// mood-based attribute-selector color overrides, and the layered background.
})();
// --- hooks/bootstrap.js ---
(function () {
	'use strict';

	const G = window.FuwaGomen || (window.FuwaGomen = {});

	const loadOnce = (id, createNode) => {
		if (document.getElementById(id)) return;
		const node = createNode();
		node.id = id;
		document.head.appendChild(node);
	};

	// Reliable kaomoji depend on the rounded font being present; GSAP drives the
	// feed animation. The font is loaded from Google Fonts; GSAP stays vendored
	// locally so the Lua runtime does not depend on a CDN to animate.
	const ensureExternalDependencies = () => {
		loadOnce('fuwa-gomen-fonts', () => {
			const link = document.createElement('link');
			link.rel = 'stylesheet';
			link.href =
				'https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c:wght@500;700;800;900&family=Nunito:wght@600;700;800;900&display=swap';
			return link;
		});
		loadOnce('fuwa-gomen-gsap', () => {
			const script = document.createElement('script');
			script.src = '/vendor/gsap/gsap-3.15.0.min.js';
			return script;
		});
	};

	// Hot-swap cleanup from a previous mount (decay timer, etc).
	if (typeof window.__fuwaGomenCleanup === 'function') {
		try {
			window.__fuwaGomenCleanup();
		} catch (error) {
			/* previous cleanup failed — ignore */
		}
		window.__fuwaGomenCleanup = null;
	}

	ensureExternalDependencies();
	console.log('[browser] Fuwa Gomen ready');

	const root = document.getElementById('gomen');
	const ds = root ? root.dataset : {};

	G.bootstrap = {
		root,
		queryRef: (name) => (root ? root.querySelector(`[data-ref="${name}"]`) : null),
		queryRefs: (name) => (root ? Array.from(root.querySelectorAll(`[data-ref="${name}"]`)) : []),
		// Seeded by the Fuwa index action via data-* on the root (real DB state).
		initialState: {
			balance: Number(ds.balance),
			spent: Number(ds.spent),
			pokes: Number(ds.pokes)
		}
	};
})();

// --- hooks/content.js ---
(function () {
	'use strict';

	const G = window.FuwaGomen || (window.FuwaGomen = {});

	// Blush cheeks (˶) are wrapped so CSS can tint them pink; rendered via innerHTML.
	// All glyphs are taken from the proven feed-me set so they render with the
	// rounded font instead of falling back to tofu.
	const blush = (s) => `<span class="blush">˶</span>${s}<span class="blush">˶</span>`;

	G.content = {
		FACES: {
			neutral: `( ${blush('• ᵕ •')} )`,
			stern: '( ¬_¬ )',
			annoyed: '（ꐦ ¬_¬ ）',
			tantrum: '(ᗒ ᗣ ᗕ)՞',
			worried: `( ${blush('˃ ⤙ ˂')} )`,
			happy: `( ${blush('≧ ᗜ ≦')} )`,
			crying: '( ╥﹏╥ )',
			// transient (animation only)
			open: `( ${blush('• 〇 •')} )`,
			chew: `( ${blush('> ﹏ <')} )`,
			angry: '( ಠ ∧ ಠ )'
		},

		COPY: {
			neutral: { jp: 'ふむ…', en: 'Mama is watching.' },
			stern: { jp: 'こら。', en: 'Behave yourself.' },
			annoyed: { jp: 'やめてって。', en: 'Quit poking me!' },
			tantrum: { jp: 'もう！知らない！', en: "That's IT!" },
			worried: { jp: 'あぶないよ…', en: 'Money is low...' },
			happy: { jp: 'えらいね！', en: 'Good job saving!' },
			crying: { jp: 'ぜんぶ使ったの…', en: 'Papa is crying...' },
			refuse: { jp: 'おかね、ない！', en: 'No money left!' }
		},

		ITEMS: [
			{ id: 'onigiri', icon: '🍙', name: 'Onigiri', price: 50 },
			{ id: 'ramen', icon: '🍜', name: 'Ramen', price: 120 },
			{ id: 'takoyaki', icon: '🐙', name: 'Takoyaki', price: 200 },
			{ id: 'sushi', icon: '🍣', name: 'Sushi', price: 300 }
		],

		CONFIG: {
			allowance: 1000,
			decayMs: 4000,
			flyMs: 520,
			chewMs: 420
		}
	};
})();

// --- hooks/mood.js ---
(function () {
	'use strict';

	const G = window.FuwaGomen || (window.FuwaGomen = {});

	// Single source of truth for Mama's face. Pure function of the two schemas'
	// numbers (wallet.balance + mood.pokes). Guard order = mood priority; the
	// first matching rule wins. Mirrors the agreed matrix exactly.
	G.mood = {
		derive(balance, pokes) {
			const F = G.content.FACES;
			const C = G.content.COPY;
			let key;

			if (balance <= 0) key = 'crying';
			else if (pokes >= 5) key = 'tantrum';
			else if (balance < 300) key = 'worried';
			else if (pokes >= 3) key = 'annoyed';
			else if (pokes >= 1) key = 'stern';
			else if (balance >= 800) key = 'happy';
			else key = 'neutral';

			return {
				moodKey: key,
				face: F[key],
				jp: C[key].jp,
				en: C[key].en,
				papa: balance <= 0
			};
		}
	};
})();

// --- hooks/fx.js ---
(function () {
	'use strict';

	const G = window.FuwaGomen || (window.FuwaGomen = {});

	// GSAP animation layer. Everything degrades gracefully to "instant" when GSAP
	// has not loaded yet, so gameplay never blocks on the CDN.
	G.fx = {
		createFx(root, queryRef) {
			const cfg = G.content.CONFIG;

			const flyFoodToMouth = (foodEl, onArrive, onDone) => {
				const gsap = window.gsap;
				const mouth = queryRef('mouth');
				if (!gsap || !foodEl || !mouth) {
					if (onArrive) onArrive();
					if (onDone) onDone();
					return;
				}

				const icon = foodEl.querySelector('.fg-food-icon') || foodEl;
				const fr = icon.getBoundingClientRect();
				const mr = mouth.getBoundingClientRect();

				const clone = icon.cloneNode(true);
				clone.style.position = 'fixed';
				clone.style.left = `${fr.left}px`;
				clone.style.top = `${fr.top}px`;
				clone.style.margin = '0';
				clone.style.zIndex = '9999';
				clone.style.pointerEvents = 'none';
				document.body.appendChild(clone);

				const dx = mr.left + mr.width / 2 - (fr.left + fr.width / 2);
				const dy = mr.top + mr.height / 2 - (fr.top + fr.height / 2);
				const total = cfg.flyMs / 1000;

				let arrived = false;
				const arrive = () => {
					if (arrived) return;
					arrived = true;
					if (onArrive) onArrive();
				};

				gsap
					.timeline({
						onComplete: () => {
							clone.remove();
							if (onDone) onDone();
						}
					})
					.to(clone, {
						x: dx * 0.6,
						y: dy * 0.6 - 28,
						scale: 1.4,
						duration: total * 0.6,
						ease: 'power1.out'
					})
					.add(arrive)
					.to(clone, {
						x: dx,
						y: dy,
						scale: 0.2,
						opacity: 0,
						duration: total * 0.4,
						ease: 'power1.in'
					});
			};

			const chew = () => {
				const gsap = window.gsap;
				const mouth = queryRef('mouth');
				if (!gsap || !mouth) return;
				gsap.fromTo(
					mouth,
					{ scale: 1 },
					{ scale: 1.12, duration: cfg.chewMs / 1000 / 2, yoyo: true, repeat: 1, ease: 'power1.inOut' }
				);
			};

			const pokeReact = () => {
				const gsap = window.gsap;
				if (!gsap || !root) return;
				gsap.fromTo(root, { x: 0 }, { x: -6, duration: 0.05, yoyo: true, repeat: 5, ease: 'power1.inOut' });
			};

			const spit = (foodEl) => {
				const gsap = window.gsap;
				if (!gsap || !foodEl) return;
				gsap.fromTo(foodEl, { y: 0 }, { y: -8, duration: 0.08, yoyo: true, repeat: 3, ease: 'power1.out' });
			};

			return { flyFoodToMouth, chew, pokeReact, spit };
		}
	};
})();

// --- hooks/game.js ---
(function () {
	'use strict';

	const G = window.FuwaGomen || (window.FuwaGomen = {});

	// petite-vue provides the @click wiring via v-scope="FuwaGomen.createScope()".
	// Gameplay state lives in the closure object `S`; all visual updates are done
	// imperatively through data-ref nodes (the donor fuwa-gomen idiom), so we do
	// not depend on capturing petite-vue's reactive proxy. The server owns
	// durability: each action fires a fire-and-forget XHR to its Fuwa route.
	G.createScope = function createScope() {
		const boot = G.bootstrap;
		const C = G.content;
		const cfg = C.CONFIG;
		const init = boot.initialState;
		const fx = G.fx.createFx(boot.root, boot.queryRef);

		const byId = {};
		C.ITEMS.forEach((it) => {
			byId[it.id] = it;
		});

		const S = {
			balance: Number.isFinite(init.balance) ? init.balance : cfg.allowance,
			spent: Number.isFinite(init.spent) ? init.spent : 0,
			pokes: Number.isFinite(init.pokes) ? init.pokes : 0,
			counts: {},
			animating: false
		};

		const ref = (name) => boot.queryRef(name);

		const setFace = (html) => {
			const mouth = ref('mouth');
			if (mouth) mouth.innerHTML = html;
		};

		const setBubble = (jp, en) => {
			const jpEl = ref('bubble-jp');
			const enEl = ref('bubble-en');
			if (jpEl) jpEl.textContent = jp;
			if (enEl) enEl.textContent = en;
		};

		let shownTotal = 0;

		const animateTotal = (target) => {
			const total = ref('total');
			if (!total) return;

			const gsap = window.gsap;
			if (!gsap) {
				total.textContent = `-¥${target}`;
				shownTotal = target;
				return;
			}

			const state = { value: shownTotal };
			gsap.to(state, {
				value: target,
				duration: 0.45,
				ease: 'power1.out',
				onUpdate: () => {
					total.textContent = `-¥${Math.round(state.value)}`;
				},
				onComplete: () => {
					shownTotal = target;
				}
			});
		};

		const renderReceipt = () => {
			const list = ref('receipt');
			if (!list) return;

			list.innerHTML = '';
			let total = 0;

			C.ITEMS.forEach((it) => {
				const qty = S.counts[it.id] || 0;
				if (!qty) return;

				const line = qty * it.price;
				total += line;

				const row = document.createElement('div');
				row.className = 'fg-receipt-row';
				row.innerHTML =
					`<span class="fg-receipt-icon">${it.icon}</span>` +
					`<span class="fg-receipt-name">${it.name}</span>` +
					`<span class="fg-receipt-qty">×${qty}</span>` +
					'<span class="fg-receipt-dots"></span>' +
					`<span class="fg-receipt-price">-¥${line}</span>`;
				list.appendChild(row);
			});

			animateTotal(total);
		};

		const seedCounts = () => {
			const seed = ref('seed');
			if (!seed) return;

			seed.querySelectorAll('[data-id]').forEach((el) => {
				const id = el.getAttribute('data-id');
				if (id && byId[id]) {
					S.counts[id] = (S.counts[id] || 0) + 1;
				}
			});

			seed.remove();
		};

		const setBar = () => {
			const fill = ref('fill');
			const text = ref('bar-text');
			const percent = Math.max(0, Math.min(100, S.balance / (cfg.allowance / 100)));

			if (fill) {
				fill.style.width = `${percent}%`;
				fill.classList.toggle('is-low', S.balance < 300);
			}

			if (text) {
				text.textContent = `¥${S.balance} · spent ¥${S.spent}`;
			}
		};

		const render = () => {
			const mood = G.mood.derive(S.balance, S.pokes);
			setFace(mood.face);
			setBubble(mood.jp, mood.en);

			if (boot.root) {
				boot.root.setAttribute('data-mood', mood.moodKey);
			}

			const papa = ref('papa');
			if (papa) {
				papa.style.display = mood.papa ? 'flex' : 'none';
			}

			setBar();
		};

		const persist = (url) => {
			try {
				// Use XMLHttpRequest, not fetch: the tenant bridge shims XHR into
				// the in-browser Lua app, which is where the DB mutation lives.
				const xhr = new XMLHttpRequest();
				xhr.open('GET', url);
				xhr.send();
			} catch (error) {
				/* offline / sandbox — client stays optimistic */
			}
		};

		const decayTimer = window.setInterval(() => {
			if (S.pokes > 0) {
				S.pokes -= 1;
				render();
				persist('/cooldown');
			}
		}, cfg.decayMs);

		window.__fuwaGomenCleanup = () => {
			window.clearInterval(decayTimer);
			window.__fuwaGomenCleanup = null;
		};

		seedCounts();
		render();
		renderReceipt();

		return {
			feed(id, event) {
				if (S.animating) return;

				const item = byId[id];
				if (!item) return;

				const foodEl = event && event.currentTarget;
				if (S.balance < item.price) {
					setFace(C.FACES.angry);
					setBubble(C.COPY.refuse.jp, C.COPY.refuse.en);
					fx.spit(foodEl);
					window.setTimeout(render, 900);
					return;
				}

				S.animating = true;
				setFace(C.FACES.open);

				fx.flyFoodToMouth(
					foodEl,
					() => {
						S.balance -= item.price;
						S.spent += item.price;
						S.counts[id] = (S.counts[id] || 0) + 1;
						setBar();
						setFace(C.FACES.chew);
						fx.chew();
						renderReceipt();
					},
					() => {
						S.animating = false;
						render();
						persist(`/buy/${id}`);
					}
				);
			},

			poke() {
				S.pokes += 1;
				render();
				fx.pokeReact();
				persist('/poke');
			},

			pet() {
				S.pokes = 0;
				render();
				persist('/calm');
			},

			askPapa() {
				S.balance = cfg.allowance;
				S.spent = 0;
				S.pokes = 0;
				S.counts = {};
				renderReceipt();
				render();
				persist('/reset');
			}
		};
	};

	// The vendored petite-vue IIFE does not self-mount without an `init`
	// attribute. Direct payload routes need an explicit mount, while the tenant
	// iframe runtime mounts the document after scripts are replayed.
	const mountApp = () => {
		const isTenantRuntime = document.body && document.body.dataset && document.body.dataset.browserRuntime === 'tenant';
		if (!isTenantRuntime && window.PetiteVue && typeof window.PetiteVue.createApp === 'function' && G.bootstrap.root) {
			window.PetiteVue.createApp().mount(G.bootstrap.root);
		}
	};

	if (document.readyState === 'loading') {
		document.addEventListener('DOMContentLoaded', mountApp, { once: true });
	} else {
		mountApp();
	}
})();
