// @ts-nocheck
// fuwa-gomen / browser.js
// Generated from hooks/*.js. Do not edit this file by hand.

// --- hooks/style.js ---
(function () {
	'use strict';

	const STYLE_ID = 'fuwa-gomen-styles';
	if (document.getElementById(STYLE_ID)) return;

	const css = `
#gomen[v-cloak]{display:none}
main.phone-screen{
	position:relative;
	display:flex;
	flex-direction:column;
	width:100%;
	height:100%;
	min-height:100%;
	overflow:hidden;
}
#gomen{
	--ink:#2a2320;
	--cream:#fff8ef;
	--pink:#f9a8c4;
	--pink-deep:#e7558b;
	--sakura:#f472b6;
	position:relative;
	flex:1 1 auto;
	align-self:stretch;
	width:100%;
	min-height:0;
	overflow:hidden;
	display:flex;
	flex-direction:column;
	gap:10px;
	padding:38px 14px 18px;
	background:
		radial-gradient(#f0ddc8 1.4px, transparent 1.4px) 0 0 / 22px 22px,
		linear-gradient(180deg,#fff8ef 0%,#fdeede 100%);
	color:var(--ink);
	font-family:'M PLUS Rounded 1c','Nunito',system-ui,sans-serif;
	-webkit-tap-highlight-color:transparent;
	user-select:none;
}
#gomen *{box-sizing:border-box}

/* budget bar */
#gomen .fg-bar{
	position:relative;
	height:24px;
	border:2px solid var(--ink);
	border-radius:999px;
	background:#efe6da;
	overflow:hidden;
}
#gomen .fg-fill{
	position:absolute;inset:0 auto 0 0;height:100%;
	background:linear-gradient(90deg,#86efac,#4ade80);
	transition:width .4s cubic-bezier(.34,1.4,.5,1);
}
#gomen .fg-fill.is-low{background:linear-gradient(90deg,#fca5a5,#f87171)}
#gomen .fg-bar-text{
	position:absolute;inset:0;display:flex;align-items:center;justify-content:center;
	font-size:11px;font-weight:800;color:var(--ink);text-shadow:0 1px 0 rgba(255,255,255,.7);
	white-space:nowrap;
}

/* speech bubble */
#gomen .fg-bubble{
	position:relative;align-self:center;max-width:92%;
	margin-top:2px;padding:8px 14px;
	background:#fff;border:2px solid var(--ink);border-radius:14px;
	box-shadow:2px 3px 0 var(--sakura);
	text-align:center;display:flex;flex-direction:column;gap:1px;
}
#gomen .fg-bubble b{font-size:14px;font-weight:900}
#gomen .fg-bubble span{font-size:11px;font-weight:700;color:#6b5e57}
#gomen .fg-bubble::after{
	content:'';position:absolute;bottom:-9px;left:50%;transform:translateX(-50%);
	border-width:9px 7px 0;border-style:solid;border-color:var(--ink) transparent transparent;
}

/* mascot */
#gomen .fg-kao{
	align-self:center;
	font-family:'M PLUS Rounded 1c',sans-serif;
	font-weight:900;font-size:clamp(44px,17vw,58px);line-height:1;
	white-space:nowrap;color:var(--ink);
	will-change:transform;
}
#gomen .fg-kao .blush{color:var(--sakura)}
#gomen .fg-name{align-self:center;font-size:10px;font-weight:800;letter-spacing:.22em;color:#b7a79e}

#gomen[data-mood="tantrum"] .fg-kao{color:#dc2626}
#gomen[data-mood="annoyed"] .fg-kao{color:#b45309}
#gomen[data-mood="stern"] .fg-kao{color:#9a6a2f}
#gomen[data-mood="worried"] .fg-kao{color:#a16207}
#gomen[data-mood="happy"] .fg-kao{color:var(--pink-deep)}
#gomen[data-mood="crying"] .fg-kao{color:#5b6b8c}

/* papa */
#gomen .fg-papa{
	align-self:center;display:none;align-items:center;gap:6px;
	padding:4px 12px;background:#e0ecff;border:2px solid #3b5b8c;border-radius:12px;
	font-size:11px;font-weight:800;color:#2d4a78;
}
#gomen .fg-papa-kao{font-size:15px;font-weight:900}

/* food shelf (tight row, fits 4 at 320px) */
#gomen .fg-shelf{display:flex;gap:6px;margin-top:2px}
#gomen .fg-food{
	flex:1 1 0;min-width:0;
	display:flex;flex-direction:column;align-items:center;gap:2px;
	padding:6px 4px;background:#fff;border:2px solid var(--ink);border-radius:10px;
	box-shadow:0 3px 0 var(--ink);cursor:pointer;font-family:inherit;
	transition:transform .08s,box-shadow .08s;
}
#gomen .fg-food:active{transform:translateY(3px);box-shadow:0 0 0 var(--ink)}
#gomen .fg-food-icon{font-size:24px;line-height:1}
#gomen .fg-food-price{
	font-size:10px;font-weight:900;padding:0 6px;
	background:#fde68a;border:1.5px solid var(--ink);border-radius:7px;color:#5c3b00;
}

/* receipt / ledger (one row per purchase) */
#gomen .fg-receipt{
	background:#fffdf8;border:2px dashed #cdbfae;border-radius:10px;padding:6px 10px;
}
#gomen .fg-receipt-head{
	font-size:9px;font-weight:900;letter-spacing:.18em;color:#a8907a;
	text-align:center;margin-bottom:4px;
}
#gomen .fg-receipt-list{display:flex;flex-direction:column;gap:3px;max-height:96px;overflow-y:auto}
#gomen .fg-receipt-row{
	display:flex;align-items:center;gap:5px;
	font-family:'Nunito',monospace;font-size:12px;font-weight:800;color:#5c4d44;
}
#gomen .fg-receipt-icon{flex-shrink:0;font-size:14px}
#gomen .fg-receipt-name{flex-shrink:0}
#gomen .fg-receipt-qty{flex-shrink:0;font-size:11px;color:#a8907a}
#gomen .fg-receipt-dots{flex:1;border-bottom:1.5px dotted #d8cab8;height:0;min-width:8px}
#gomen .fg-receipt-price{flex-shrink:0;color:#b45309}
#gomen .fg-receipt-total{
	display:flex;align-items:center;gap:5px;margin-top:5px;padding-top:5px;
	border-top:2px solid #cdbfae;
	font-family:'Nunito',monospace;font-size:13px;font-weight:900;color:#2a2320;
}
#gomen .fg-receipt-total-label{flex-shrink:0}
#gomen .fg-receipt-total-val{flex-shrink:0;color:#b45309}

/* kaomoji action buttons */
#gomen .fg-actions{display:flex;gap:6px;margin-top:2px}
#gomen .fg-btn{
	flex:1;padding:8px 4px;border:2px solid var(--ink);border-radius:10px;
	background:#fff;color:var(--ink);font-family:inherit;font-size:12px;font-weight:900;
	cursor:pointer;box-shadow:0 3px 0 var(--ink);white-space:nowrap;
	transition:transform .08s,box-shadow .08s;
}
#gomen .fg-btn:active{transform:translateY(3px);box-shadow:0 0 0 var(--ink)}
`;

	const style = document.createElement('style');
	style.id = STYLE_ID;
	style.textContent = css;
	document.head.appendChild(style);
})();

// --- hooks/bootstrap.js ---
(function () {
	'use strict';

	const G = window.FuwaGomen || (window.FuwaGomen = {});

	const loadOnce = (id, createNode) => {
		if (document.getElementById(id)) return;
		const node = createNode();
		node.id = id;
		document.head.appendChild(node);
	};

	// Reliable kaomoji depend on the rounded font being present; GSAP drives the
	// feed animation. Both are loaded once, from CDN, the same way gomen-v2 does.
	const ensureExternalDependencies = () => {
		loadOnce('fuwa-gomen-fonts', () => {
			const link = document.createElement('link');
			link.rel = 'stylesheet';
			link.href =
				'https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c:wght@500;700;800;900&family=Nunito:wght@600;700;800;900&display=swap';
			return link;
		});
		loadOnce('fuwa-gomen-gsap', () => {
			const script = document.createElement('script');
			script.src = 'https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/gsap.min.js';
			return script;
		});
	};

	// Hot-swap cleanup from a previous mount (decay timer, etc).
	if (typeof window.__fuwaGomenCleanup === 'function') {
		try {
			window.__fuwaGomenCleanup();
		} catch (error) {
			/* previous cleanup failed — ignore */
		}
		window.__fuwaGomenCleanup = null;
	}

	ensureExternalDependencies();
	console.log('[browser] Fuwa Gomen ready');

	const root = document.getElementById('gomen');
	const ds = root ? root.dataset : {};

	G.bootstrap = {
		root,
		queryRef: (name) => (root ? root.querySelector(`[data-ref="${name}"]`) : null),
		queryRefs: (name) => (root ? Array.from(root.querySelectorAll(`[data-ref="${name}"]`)) : []),
		// Seeded by the Fuwa `index` action via data-* on the root (real DB state).
		initialState: {
			balance: Number(ds.balance),
			spent: Number(ds.spent),
			pokes: Number(ds.pokes)
		}
	};
})();

// --- hooks/content.js ---
(function () {
	'use strict';

	const G = window.FuwaGomen || (window.FuwaGomen = {});

	// Blush cheeks (˶) are wrapped so CSS can tint them pink; rendered via innerHTML.
	// All glyphs are taken from the proven feed-me set so they render with the
	// rounded font instead of falling back to tofu.
	const blush = (s) => `<span class="blush">˶</span>${s}<span class="blush">˶</span>`;

	G.content = {
		FACES: {
			neutral: `( ${blush('• ᵕ •')} )`,
			stern: '( ¬_¬ )',
			annoyed: '（ꐦ ¬_¬ ）',
			tantrum: '(ᗒ ᗣ ᗕ)՞',
			worried: `( ${blush('˃ ⤙ ˂')} )`,
			happy: `( ${blush('≧ ᗜ ≦')} )`,
			crying: '( ╥﹏╥ )',
			// transient (animation only)
			open: `( ${blush('• 〇 •')} )`,
			chew: `( ${blush('> ﹏ <')} )`,
			angry: '( ಠ ∧ ಠ )'
		},

		COPY: {
			neutral: { jp: 'ふむ…', en: 'Mama is watching.' },
			stern: { jp: 'こら。', en: 'Behave yourself.' },
			annoyed: { jp: 'やめてって。', en: 'Quit poking me!' },
			tantrum: { jp: 'もう！知らない！', en: "That's IT!" },
			worried: { jp: 'あぶないよ…', en: 'Money is low...' },
			happy: { jp: 'えらいね！', en: 'Good job saving!' },
			crying: { jp: 'ぜんぶ使ったの…', en: 'Papa is crying...' },
			refuse: { jp: 'おかね、ない！', en: 'No money left!' }
		},

		ITEMS: [
			{ id: 'onigiri', icon: '🍙', name: 'Onigiri', price: 50 },
			{ id: 'ramen', icon: '🍜', name: 'Ramen', price: 120 },
			{ id: 'takoyaki', icon: '🐙', name: 'Takoyaki', price: 200 },
			{ id: 'sushi', icon: '🍣', name: 'Sushi', price: 300 }
		],

		CONFIG: {
			allowance: 1000,
			decayMs: 4000,
			flyMs: 520,
			chewMs: 420
		}
	};
})();

// --- hooks/mood.js ---
(function () {
	'use strict';

	const G = window.FuwaGomen || (window.FuwaGomen = {});

	// Single source of truth for Mama's face. Pure function of the two schemas'
	// numbers (wallet.balance + mood.pokes). Guard order = mood priority; the
	// first matching rule wins. Mirrors the agreed matrix exactly.
	G.mood = {
		derive(balance, pokes) {
			const F = G.content.FACES;
			const C = G.content.COPY;
			let key;

			if (balance <= 0) key = 'crying';
			else if (pokes >= 5) key = 'tantrum';
			else if (balance < 300) key = 'worried';
			else if (pokes >= 3) key = 'annoyed';
			else if (pokes >= 1) key = 'stern';
			else if (balance >= 800) key = 'happy';
			else key = 'neutral';

			return {
				moodKey: key,
				face: F[key],
				jp: C[key].jp,
				en: C[key].en,
				papa: balance <= 0
			};
		}
	};
})();

// --- hooks/fx.js ---
(function () {
	'use strict';

	const G = window.FuwaGomen || (window.FuwaGomen = {});

	// GSAP animation layer. Everything degrades gracefully to "instant" when GSAP
	// has not loaded yet, so gameplay never blocks on the CDN.
	G.fx = {
		createFx(root, queryRef) {
			const cfg = G.content.CONFIG;

			const flyFoodToMouth = (foodEl, onArrive, onDone) => {
				const gsap = window.gsap;
				const mouth = queryRef('mouth');
				if (!gsap || !foodEl || !mouth) {
					if (onArrive) onArrive();
					if (onDone) onDone();
					return;
				}

				const icon = foodEl.querySelector('.fg-food-icon') || foodEl;
				const fr = icon.getBoundingClientRect();
				const mr = mouth.getBoundingClientRect();

				const clone = icon.cloneNode(true);
				clone.style.position = 'fixed';
				clone.style.left = `${fr.left}px`;
				clone.style.top = `${fr.top}px`;
				clone.style.margin = '0';
				clone.style.zIndex = '9999';
				clone.style.pointerEvents = 'none';
				document.body.appendChild(clone);

				const dx = mr.left + mr.width / 2 - (fr.left + fr.width / 2);
				const dy = mr.top + mr.height / 2 - (fr.top + fr.height / 2);
				const total = cfg.flyMs / 1000;

				let arrived = false;
				const arrive = () => {
					if (arrived) return;
					arrived = true;
					if (onArrive) onArrive();
				};

				gsap
					.timeline({
						onComplete: () => {
							clone.remove();
							if (onDone) onDone();
						}
					})
					.to(clone, {
						x: dx * 0.6,
						y: dy * 0.6 - 28,
						scale: 1.4,
						duration: total * 0.6,
						ease: 'power1.out'
					})
					.add(arrive)
					.to(clone, {
						x: dx,
						y: dy,
						scale: 0.2,
						opacity: 0,
						duration: total * 0.4,
						ease: 'power1.in'
					});
			};

			const chew = () => {
				const gsap = window.gsap;
				const mouth = queryRef('mouth');
				if (!gsap || !mouth) return;
				gsap.fromTo(
					mouth,
					{ scale: 1 },
					{ scale: 1.12, duration: cfg.chewMs / 1000 / 2, yoyo: true, repeat: 1, ease: 'power1.inOut' }
				);
			};

			const pokeReact = () => {
				const gsap = window.gsap;
				if (!gsap || !root) return;
				gsap.fromTo(root, { x: 0 }, { x: -6, duration: 0.05, yoyo: true, repeat: 5, ease: 'power1.inOut' });
			};

			const spit = (foodEl) => {
				const gsap = window.gsap;
				if (!gsap || !foodEl) return;
				gsap.fromTo(foodEl, { y: 0 }, { y: -8, duration: 0.08, yoyo: true, repeat: 3, ease: 'power1.out' });
			};

			return { flyFoodToMouth, chew, pokeReact, spit };
		}
	};
})();

// --- hooks/game.js ---
(function () {
	'use strict';

	const G = window.FuwaGomen || (window.FuwaGomen = {});

	// petite-vue provides the @click wiring via v-scope="FuwaGomen.createScope()".
	// Gameplay state lives in the closure object `S`; all visual updates are done
	// imperatively through data-ref nodes (the gomen-v2 / postbox idiom), so we do
	// NOT depend on capturing petite-vue's reactive proxy. The server owns
	// durability: each action fires a fire-and-forget XHR to its Fuwa route.
	G.createScope = function createScope() {
		const boot = G.bootstrap;
		const C = G.content;
		const cfg = C.CONFIG;
		const init = boot.initialState;
		const fx = G.fx.createFx(boot.root, boot.queryRef);

		const byId = {};
		C.ITEMS.forEach((it) => {
			byId[it.id] = it;
		});

		const S = {
			balance: Number.isFinite(init.balance) ? init.balance : cfg.allowance,
			spent: Number.isFinite(init.spent) ? init.spent : 0,
			pokes: Number.isFinite(init.pokes) ? init.pokes : 0,
			counts: {}, // item id -> quantity bought
			animating: false
		};

		const ref = (name) => boot.queryRef(name);

		const setFace = (html) => {
			const mouth = ref('mouth');
			if (mouth) mouth.innerHTML = html;
		};

		const setBubble = (jp, en) => {
			const j = ref('bubble-jp');
			const e = ref('bubble-en');
			if (j) j.textContent = jp;
			if (e) e.textContent = en;
		};

		// ── receipt (aggregated: one line per item, ×qty, line total) ──────────
		let shownTotal = 0;

		const animateTotal = (target) => {
			const el = ref('total');
			if (!el) return;
			const gsap = window.gsap;
			if (!gsap) {
				el.textContent = `-¥${target}`;
				shownTotal = target;
				return;
			}
			const obj = { v: shownTotal };
			gsap.to(obj, {
				v: target,
				duration: 0.45,
				ease: 'power1.out',
				onUpdate: () => {
					el.textContent = `-¥${Math.round(obj.v)}`;
				},
				onComplete: () => {
					shownTotal = target;
				}
			});
		};

		const renderReceipt = () => {
			const list = ref('receipt');
			if (!list) return;
			list.innerHTML = '';
			let total = 0;
			C.ITEMS.forEach((it) => {
				const qty = S.counts[it.id] || 0;
				if (!qty) return;
				const line = qty * it.price;
				total += line;
				const row = document.createElement('div');
				row.className = 'fg-receipt-row';
				row.innerHTML =
					`<span class="fg-receipt-icon">${it.icon}</span>` +
					`<span class="fg-receipt-name">${it.name}</span>` +
					`<span class="fg-receipt-qty">×${qty}</span>` +
					'<span class="fg-receipt-dots"></span>' +
					`<span class="fg-receipt-price">-¥${line}</span>`;
				list.appendChild(row);
			});
			animateTotal(total);
		};

		// Seed counts from the server-rendered ledger rows, then drop the seed.
		const seedCounts = () => {
			const seed = ref('seed');
			if (!seed) return;
			seed.querySelectorAll('[data-id]').forEach((el) => {
				const id = el.getAttribute('data-id');
				if (id && byId[id]) S.counts[id] = (S.counts[id] || 0) + 1;
			});
			seed.remove();
		};

		const setBar = () => {
			const fill = ref('fill');
			const text = ref('bar-text');
			const pct = Math.max(0, Math.min(100, S.balance / (cfg.allowance / 100)));
			if (fill) {
				fill.style.width = `${pct}%`;
				fill.classList.toggle('is-low', S.balance < 300);
			}
			if (text) text.textContent = `¥${S.balance} · spent ¥${S.spent}`;
		};

		// Paint the derived mood (face + bubble + papa + tint) from S.
		const render = () => {
			const d = G.mood.derive(S.balance, S.pokes);
			setFace(d.face);
			setBubble(d.jp, d.en);
			if (boot.root) boot.root.setAttribute('data-mood', d.moodKey);
			const papa = ref('papa');
			if (papa) papa.style.display = d.papa ? 'flex' : 'none';
			setBar();
		};

		const persist = (url) => {
			try {
				// Use XMLHttpRequest, not fetch: the runtime bridge shims
				// window.XMLHttpRequest to route same-origin app routes into the
				// in-browser Lua server (which writes the DB). A raw fetch()
				// bypasses that shim and hits the real origin, so the Fuwa action
				// never runs. Fire-and-forget — we ignore the reply (no DOM swap),
				// the client already painted optimistically.
				const xhr = new XMLHttpRequest();
				xhr.open('GET', url);
				xhr.send();
			} catch (error) {
				/* offline / sandbox — client stays optimistic */
			}
		};

		// Anger cools down on its own; /cooldown keeps the DB in step.
		const decayTimer = window.setInterval(() => {
			if (S.pokes > 0) {
				S.pokes -= 1;
				render();
				persist('/cooldown');
			}
		}, cfg.decayMs);

		window.__fuwaGomenCleanup = () => {
			window.clearInterval(decayTimer);
			window.__fuwaGomenCleanup = null;
		};

		// initial paint from real DB state
		seedCounts();
		render();
		renderReceipt();

		return {
			feed(id, event) {
				if (S.animating) return;
				const item = byId[id];
				if (!item) return;
				const foodEl = event && event.currentTarget;

				if (S.balance < item.price) {
					setFace(C.FACES.angry);
					setBubble(C.COPY.refuse.jp, C.COPY.refuse.en);
					fx.spit(foodEl);
					window.setTimeout(render, 900);
					return;
				}

				S.animating = true;
				setFace(C.FACES.open);

				fx.flyFoodToMouth(
					foodEl,
					() => {
						S.balance -= item.price;
						S.spent += item.price;
						S.counts[id] = (S.counts[id] || 0) + 1;
						setBar();
						setFace(C.FACES.chew);
						fx.chew();
						renderReceipt();
					},
					() => {
						S.animating = false;
						render();
						persist(`/buy/${id}`);
					}
				);
			},

			poke() {
				S.pokes += 1;
				render();
				fx.pokeReact();
				persist('/poke');
			},

			pet() {
				S.pokes = 0;
				render();
				persist('/calm');
			},

			askPapa() {
				S.balance = cfg.allowance;
				S.spent = 0;
				S.pokes = 0;
				S.counts = {};
				renderReceipt();
				render();
				persist('/reset');
			}
		};
	};
})();
