import { readFileSync } from 'node:fs';

import type { RuntimeFiles } from '../../engine/types';

function readText(relativePath: string): string {
	return readFileSync(new URL(relativePath, import.meta.url), 'utf8');
}

function buildBrowserJs(): string {
	const chunks = [
		'// @ts-nocheck',
		'// fuwa-gomen / browser.js',
		'// Generated from hooks/*.js. Do not edit this file by hand.',
		'',
		'// --- hooks/style.js ---',
		readText('./hooks/style.js'),
		'',
		'// --- hooks/bootstrap.js ---',
		readText('./hooks/bootstrap.js'),
		'',
		'// --- hooks/content.js ---',
		readText('./hooks/content.js'),
		'',
		'// --- hooks/mood.js ---',
		readText('./hooks/mood.js'),
		'',
		'// --- hooks/fx.js ---',
		readText('./hooks/fx.js'),
		'',
		'// --- hooks/game.js ---',
		readText('./hooks/game.js')
	];

	return chunks.join('\n');
}

export const FUWA_GOMEN_ENTRY_FILE = 'app.fuwa';

export function buildFuwaGomenFiles(): RuntimeFiles {
	return {
		'app.fuwa': readText('./app.fuwa'),
		'pages/gomen.fuwa': readText('./pages/gomen.fuwa'),
		'models/wallet.fuwa': readText('./models/wallet.fuwa'),
		'models/mood.fuwa': readText('./models/mood.fuwa'),
		'models/ledger.fuwa': readText('./models/ledger.fuwa'),
		'view.fuwa': readText('./view.fuwa'),
		'hooks/style.js': readText('./hooks/style.js'),
		'hooks/bootstrap.js': readText('./hooks/bootstrap.js'),
		'hooks/content.js': readText('./hooks/content.js'),
		'hooks/mood.js': readText('./hooks/mood.js'),
		'hooks/fx.js': readText('./hooks/fx.js'),
		'hooks/game.js': readText('./hooks/game.js'),
		'browser.js': buildBrowserJs()
	};
}

export const FUWA_GOMEN_FILES: RuntimeFiles = buildFuwaGomenFiles();

export const FUWA_GOMEN_VISIBLE_FILES = [
	'app.fuwa',
	'pages/gomen.fuwa',
	'models/wallet.fuwa',
	'models/mood.fuwa',
	'models/ledger.fuwa',
	'view.fuwa',
	'hooks/style.js',
	'hooks/bootstrap.js',
	'hooks/content.js',
	'hooks/mood.js',
	'hooks/fx.js',
	'hooks/game.js',
	'browser.js'
] as const;

export const FUWA_GOMEN_BROWSER_JS = FUWA_GOMEN_FILES['browser.js'];
