-- runtime/browser/styles.lua
-- CSS styles for the browser runtime srcdoc builders.
-- Extracted from init.lua to keep the protocol logic readable.

local M = {}

-- Base scaffold styles (used by build_srcdoc)
M.base = table.concat({
	"      html, body {",
	"        width: 100%;",
	"        height: 100%;",
	"        min-height: 100%;",
	"        margin: 0;",
	"      }",
	"",
	"      body {",
	"        background: transparent;",
	"      }",
	"",
	"      #app {",
	"        min-height: 100%;",
	"      }",
}, "\n")

-- Runtime tenant styles (used by build_runtime_srcdoc)
M.runtime = table.concat({
	"      :root {",
	"        color-scheme: dark;",
	"        --phone-safe-top: 3.5rem;",
	"        --phone-safe-right: 0px;",
	"        --phone-safe-bottom: 2rem;",
	"        --phone-safe-left: 0px;",
	"        --phone-content-x: 1rem;",
	"        --phone-statusbar-height: 1rem;",
	"      }",
	"",
	"      html, body, #phone-shell, #app {",
	"        width: 100%;",
	"        height: 100%;",
	"        min-height: 100%;",
	"      }",
	"",
	"      html, body {",
	"        margin: 0;",
	"        padding: 0;",
	"      }",
	"",
	"      body {",
	"        position: relative;",
	"        overflow: hidden;",
	"        box-sizing: border-box;",
	"        background:",
	"          radial-gradient(circle at top, rgba(96, 165, 250, 0.16), transparent 30%),",
	"          radial-gradient(circle at 85% 110%, rgba(45, 212, 191, 0.1), transparent 24%),",
	"          linear-gradient(180deg, #05070d 0%, #0b1020 54%, #050608 100%);",
	"        color: #e5eef6;",
	"        font-family: system-ui, sans-serif;",
	"      }",
	"",
	"      *, *::before, *::after {",
	"        box-sizing: border-box;",
	"      }",
	"",
	"      #phone-shell {",
	"        position: relative;",
	"        overflow: hidden;",
	"        isolation: isolate;",
	"      }",
	"",
	"      #app {",
	"        position: relative;",
	"        margin: 0;",
	"        padding: 0;",
	"        overflow: hidden;",
	"        background: transparent;",
	"        color: inherit;",
	"      }",
	"",
	"      .phone-system-ui {",
	"        position: absolute;",
	"        inset: 0;",
	"        pointer-events: none;",
	"        z-index: 2;",
	"        display: flex;",
	"        flex-direction: column;",
	"        justify-content: space-between;",
	"      }",
	"",
	"      .phone-statusbar {",
	"        min-height: var(--phone-safe-top);",
	"        display: flex;",
	"        align-items: flex-start;",
	"        justify-content: space-between;",
	"        padding:",
	"          0.7rem",
	"          calc(var(--phone-safe-right) + var(--phone-content-x))",
	"          0",
	"          calc(var(--phone-safe-left) + var(--phone-content-x));",
	"        font-size: 0.69rem;",
	"        line-height: var(--phone-statusbar-height);",
	"        font-weight: 600;",
	"        letter-spacing: 0.02em;",
	"        color: #f3f4f6;",
	"      }",
	"",
	"      .phone-statusbar-icons {",
	"        display: inline-flex;",
	"        align-items: center;",
	"        gap: 0.35rem;",
	"      }",
	"",
	"      .phone-home-indicator {",
	"        align-self: center;",
	"        margin-bottom: 0.5rem;",
	"        width: 124px;",
	"        height: 4px;",
	"        border-radius: 999px;",
	"        background: rgba(255, 255, 255, 0.22);",
	"      }",
	"",
	"      .phone-screen {",
	"        position: relative;",
	"        min-height: 100%;",
	"        height: 100%;",
	"        display: flex;",
	"        flex-direction: column;",
	"        background: transparent;",
	"        color: inherit;",
	"      }",
	"",
	"      .phone-screen-scroll {",
	"        min-height: 100%;",
	"        overflow-x: hidden;",
	"        overflow-y: auto;",
	"        overscroll-behavior-y: contain;",
	"        -webkit-overflow-scrolling: touch;",
	"      }",
	"",
	"      .phone-safe-top { padding-top: var(--phone-safe-top); }",
	"      .phone-safe-bottom { padding-bottom: var(--phone-safe-bottom); }",
	"",
	"      .phone-safe-x {",
	"        padding-left: calc(var(--phone-safe-left) + var(--phone-content-x));",
	"        padding-right: calc(var(--phone-safe-right) + var(--phone-content-x));",
	"      }",
	"",
	"      .phone-safe-all {",
	"        padding:",
	"          var(--phone-safe-top)",
	"          calc(var(--phone-safe-right) + var(--phone-content-x))",
	"          var(--phone-safe-bottom)",
	"          calc(var(--phone-safe-left) + var(--phone-content-x));",
	"      }",
	"",
	"      .phone-stack { display: flex; flex-direction: column; gap: 1rem; }",
	"      .phone-section { width: 100%; }",
	"",
	"      h1 { margin: 0; font-size: 2rem; line-height: 1.05; letter-spacing: -0.04em; }",
	"      p { margin: 0; color: #94a3b8; }",
	"      form { display: grid; gap: 0.75rem; }",
	"",
	"      a, button {",
	"        display: inline-flex;",
	"        align-items: center;",
	"        justify-content: center;",
	"        width: fit-content;",
	"        min-height: 42px;",
	"        border: 0;",
	"        border-radius: 999px;",
	"        background: #163b34;",
	"        color: white;",
	"        padding: 0 1rem;",
	"        font: inherit;",
	"        text-decoration: none;",
	"      }",
	"",
	"      input, textarea, select {",
	"        box-sizing: border-box;",
	"        width: 100%;",
	"        margin: 0;",
	"        border: 1px solid #d7cbbc;",
	"        border-radius: 0.9rem;",
	"        padding: 10px 12px;",
	"        font: inherit;",
	"        background: white;",
	"        color: inherit;",
	"      }",
	"",
	"      pre { white-space: pre-wrap; word-break: break-word; }",
	"      [x-cloak] { display: none !important; }",
}, "\n")

return M
